name: empay_test
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'


dependencies:
  flutter:
    sdk: flutter

  # state
  bloc: 8.1.2
  flutter_bloc: 8.1.3
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  elementary: 3.0.0

  # ui
  gap: 3.0.1
  cupertino_icons: 1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # runner
  build_runner: 2.4.4

  # generator
  freezed: 2.4.5
  json_serializable: 6.7.1


flutter:
  uses-material-design: true
